### ISSUE TITLE
Remaining time background animation not pausing

### ISSUE THREAD

**Issue by dannerrainer** [Stevie-Ray/hangtime#31]
Hi,

love the fancy background animation, but I noticed that it does not stop in place when one pause in a rest, see the attached video.
Is this intentional?
I would think it's more intuitive if it would pause as well and finish at the same time as the countdown ends?

https://github.com/user-attachments/assets/b23a1d94-9b5b-41a5-a85a-26b01a2453cb

**Comment by Stevie-Ray** [comment]
Hi @dannerrainer,

Thanks for the feedback—glad you love the background animation!  You're absolutely right; it would feel more intuitive if the animation paused during rest and synchronized with the countdown.

I think this can be adjusted using the [animation-play-state](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state) property. 

Stevie
