### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by hleroy** [Stevie-Ray/hangtime#33]
I have noticed a couple of missing translation strings, e.g "Before hangs", "After repeats" (see screenshots).

I am not familiar with how translation works with your codebase. Would you mind regenerating the json files for translation? Then I will happily update the FR ones 😀

![Screenshot_20241124_110530_Chrome](https://github.com/user-attachments/assets/3c215d64-c361-4f75-a7e1-8d27c42bfe30)

**Comment by Stevie-Ray** [comment]
Hi @hleroy,

Thank you for pointing that out! The translation system is straightforward: you need to wrap strings in brackets like this: `{{ $('Example string') }}` to make them translatable.

The translation files are maintained manually. I'll add the missing entries:

```json
{
  "After repeats": "Après les répétitions",
  "Before hang": "À suspendre"
}
```
